apiVersion: v1
kind: Service
metadata:
  name: {{ include "embed-text.fullname" . }}
  labels:
    {{- include "embed-text.labels" . | nindent 4 }}
{{/*  annotations:*/}}
{{/*    prometheus.io/scrape: "true"*/}}
{{/*    prometheus.io/path: "/metrics"*/}}
{{/*    prometheus.io/port: "{{ .Values.service.metrics.port }}"*/}}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    {{- include "embed-text.selectorLabels" . | nindent 4 }}
